server:
  port: 9080


#Direct Dev MASST_DEV.WORLD
#spring.datasource.squema=MASST_OWNER
#spring.datasource.username=MASST_USER
#spring.datasource.password=i278IE4z
#spring.datasource.url=jdbc:oracle:thin:@cds0stl20.mastercard.int:1527:dcup1s


#spring:
  
#  datasource:
#    url: jdbc:postgresql://ech-10-157-139-107.mastercard.int:5432/postgres
#    username: postgres
#    password: start123